CREATE DATABASE journal;

USE journal;

/* TABLE FOR USERS */

CREATE TABLE users
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  PRIMARY KEY (id),
);

/* TABLE FOR JOURNAL ENTRIES - EACH TABLE ROW HAS A FOREIGN KEY THAT REFERENCES A USER ID */

CREATE TABLE entries
(
  id INT NOT NULL AUTO_INCREMENT,
  entry TEXT NOT NULL,
  dateOfEntry DATE NOT NULL,
  userId INT NOT NULL REFERENCES users(id),
  PRIMARY KEY (id)
);




